spring:
  application:
    name: Customer-Service
  profiles:
    active:
    - local
  cloud:
    config:
      fail-fast: false  #Keep false when config service is not used
      uri:
      - http://localhost:8080
  